<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends EntityRepository
{
    public function findActive(){
        //TODO Query for active survey
        //$this->createQueryBuilder($alias);
        
        return array();
    }
}
