admin_answer:
    resource: "@AdminBundle/Controller/AnswerController.php"
    type:     annotation

admin_question:
    resource: "@AdminBundle/Controller/QuestionController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller"
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
