<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function findAllOrder(){
        return $this->findBy(array(), array('survey' => 'ASC'));
    }
}
